// ─────────────────────────────────────────────────────────────────────────
//  El Diario de Sebastián — datos de las tareas (evidencias) de la materia
//  Cada "tarea" se representa como una película reseñada al estilo Letterboxd.
// ─────────────────────────────────────────────────────────────────────────

const PROFILE = {
  app: "FOTOGRAMA",
  appTagline: "Diario de cine",
  author: "Sebastian Rodríguez Arellano",
};

// variant: 'dark' | 'light' | 'accent'  — controla el tratamiento del póster tipográfico
// poster: ruta relativa a la imagen, ej. "posters/blackkklansman.jpg"
//         Si está vacío ("") se muestra el diseño tipográfico.
const FILMS = [
  {
    id: "blackkklansman",
    contentFile: "blackKKlansman",
    genre: "Drama",
    task: "Título de la tarea",
    film: "BlacKkKlansman",
    year: 2018,
    director: "Spike Lee",
    writer: "Charlie Wachtel, David Rabinowitz, Kevin Willmott, Spike Lee",
    producer: "Jordan Peele, Jason Blum, Raymond Mansfield, Sean McKittrick",
    studio: "Focus Features · Blumhouse Productions",
    cinematography: "Chayse Irvin",
    country: "Estados Unidos",
    runtime: "135 min",
    rating: 3.5,
    liked: false,
    watched: "02 Jun 2026",
    tags: ["Drama", "Comedia Biográfica"],
    variant: "dark",
    posterNo: "01",
    poster: "posters/blackKKKlansman.jpg",
    excerpt: "Spike Lee narra la insólita historia real de Ron Stallworth, quien logra infiltrarse en el Ku Klux Klan usando una inteligente comedia satírica para exponer la mecánica del odio.",
  },
  {
    id: "django",
    contentFile: "djangoUnchained",
    genre: "Western",
    task: "Título de la tarea",
    film: "Django Unchained",
    year: 2012,
    director: "Quentin Tarantino",
    writer: "Quentin Tarantino",
    producer: "Stacey Sher, Reginald Hudlin, Pilar Savone",
    studio: "Columbia Pictures · The Weinstein Company",
    cinematography: "Robert Richardson",
    country: "Estados Unidos",
    runtime: "165 min",
    rating: 4,
    liked: false,
    watched: "03 Jun 2026",
    tags: ["Western", "Drama"],
    variant: "accent",
    posterNo: "02",
    poster: "posters/djangoUnchained.jpg",
    excerpt: "Tarantino aborda la esclavitud con su mezcla explosiva de violencia estilizada, humor negro y sátira, sostenida por un elenco sobresaliente que crea una dinámica irresistible.",
  },
  {
    id: "thelma-louise",
    contentFile: "ThelmaLouise",
    genre: "Drama",
    task: "Título de la tarea",
    film: "Thelma & Louise",
    year: 1991,
    director: "Ridley Scott",
    writer: "Callie Khouri",
    producer: "Ridley Scott, Mimi Polk Gitlin",
    studio: "MGM · Pathé Entertainment",
    cinematography: "Adrian Biddle",
    country: "Estados Unidos",
    runtime: "130 min",
    rating: 3.5,
    liked: false,
    watched: "08 Jun 2026",
    tags: ["Road Movie", "Drama"],
    variant: "light",
    posterNo: "03",
    poster: "posters/thelma&Louise.jpg",
    posterZoom: 1.1,
    excerpt: "Ridley Scott dirige esta road movie icónica sobre dos mujeres que, huyendo de sus vidas cotidianas, emprenden un viaje de libertad con consecuencias irreversibles.",
  },
  {
    id: "arrival",
    contentFile: "Arrival",
    genre: "Ciencia ficción",
    task: "Título de la tarea",
    film: "Arrival",
    year: 2016,
    director: "Denis Villeneuve",
    writer: "Eric Heisserer",
    producer: "Shawn Levy, Dan Levine, Aaron Ryder, David Linde",
    studio: "Paramount Pictures · FilmNation Entertainment",
    cinematography: "Bradford Young",
    country: "Estados Unidos",
    runtime: "116 min",
    rating: 4.5,
    liked: false,
    watched: "09 Jun 2026",
    tags: ["Ciencia Ficción", "Drama"],
    variant: "dark",
    posterNo: "04",
    poster: "posters/arrival.jpg",
    excerpt: "Denis Villeneuve explora el lenguaje y el tiempo a través de una lingüista que debe descifrar la comunicación de visitantes extraterrestres antes de que el mundo entre en caos.",
  },
  {
    id: "moonrise-kingdom",
    contentFile: "MoonriseKingdom",
    genre: "Comedia / Drama",
    task: "Título de la tarea",
    film: "Moonrise Kingdom",
    year: 2012,
    director: "Wes Anderson",
    writer: "Wes Anderson, Roman Coppola",
    producer: "Wes Anderson, Scott Rudin, Steven Rales, Jeremy Dawson",
    studio: "Focus Features · Indian Paintbrush",
    cinematography: "Robert D. Yeoman",
    country: "Estados Unidos",
    runtime: "94 min",
    rating: 3,
    liked: false,
    watched: "10 Jun 2026",
    tags: ["Comedia Romántica", "Drama"],
    variant: "accent",
    posterNo: "05",
    poster: "posters/moonriseKingdom.jpg",
    excerpt: "Wes Anderson construye un cuento visual sobre dos niños que escapan juntos en una isla de Nueva Inglaterra, narrado con su característica simetría, paleta pastel y humor delicado.",
  },
  {
    id: "district-9",
    contentFile: "District9",
    genre: "Ciencia ficción",
    task: "Título de la tarea",
    film: "District 9",
    year: 2009,
    director: "Neill Blomkamp",
    writer: "Neill Blomkamp, Terri Tatchell",
    producer: "Peter Jackson, Carolynne Cunningham",
    studio: "TriStar Pictures · WingNut Films",
    cinematography: "Trent Opaloch",
    country: "Sudáfrica / Nueva Zelanda",
    runtime: "112 min",
    rating: 3.5,
    liked: false,
    watched: "15 Jun 2026",
    tags: ["Ciencia Ficción", "Thriller"],
    variant: "dark",
    posterNo: "06",
    poster: "posters/district9.jpg",
    excerpt: "Neill Blomkamp construye una potente alegoría sobre el apartheid y la xenofobia usando extraterrestres segregados en Johannesburgo, mezclando estética de documental y acción visceral.",
  },
  {
    id: "children-of-men",
    contentFile: "childrenOfMen",
    genre: "Ciencia ficción",
    task: "Título de la tarea",
    film: "Children of Men",
    year: 2006,
    director: "Alfonso Cuarón",
    writer: "Alfonso Cuarón, Timothy J. Sexton, David Arata, Mark Fergus, Hawk Ostby",
    producer: "Marc Abraham, Eric Newman, Hilary Shor, Iain Smith, Tony Smith",
    studio: "Universal Pictures · Strike Entertainment",
    cinematography: "Emmanuel Lubezki",
    country: "Reino Unido / Estados Unidos",
    runtime: "109 min",
    rating: 4,
    liked: false,
    watched: "16 Jun 2026",
    tags: ["Ciencia Ficción", "Thriller Distópico"],
    variant: "light",
    posterNo: "07",
    poster: "posters/childrenOfMen.jpg",
    excerpt: "Alfonso Cuarón dirige este escalofriante thriller distópico en un mundo sin nuevos nacimientos, memorable por sus extraordinarios planos secuencia y su humanismo desesperanzador.",
  },
  {
    id: "silence-of-the-lambs",
    contentFile: "silenceOfTheLambs",
    genre: "Thriller / Terror",
    task: "Título de la tarea",
    film: "The Silence of the Lambs",
    year: 1991,
    director: "Jonathan Demme",
    writer: "Ted Tally",
    producer: "Edward Saxon, Kenneth Utt, Ron Bozman",
    studio: "Orion Pictures",
    cinematography: "Tak Fujimoto",
    country: "Estados Unidos",
    runtime: "118 min",
    rating: 4.5,
    liked: false,
    watched: "17 Jun 2026",
    tags: ["Thriller", "Terror Psicológico"],
    variant: "dark",
    posterNo: "08",
    poster: "posters/silenceOfTheLambs.jpg",
    excerpt: "Jonathan Demme dirige este clásico del thriller psicológico donde la agente Clarice Starling debe consultar al perturbador Dr. Hannibal Lecter para atrapar a un asesino en serie.",
  },
  {
    id: "isle-of-dogs",
    contentFile: "isleOfDogs",
    genre: "Animación / Aventura",
    task: "Título de la tarea",
    film: "Isle of Dogs",
    year: 2018,
    director: "Wes Anderson",
    writer: "Wes Anderson, Roman Coppola, Jason Schwartzman, Kunichi Nomura",
    producer: "Wes Anderson, Scott Rudin, Steven Rales, Jeremy Dawson",
    studio: "Fox Searchlight Pictures · Indian Paintbrush",
    cinematography: "Tristan Oliver",
    country: "Estados Unidos / Alemania",
    runtime: "101 min",
    rating: 4,
    liked: false,
    watched: "22 Jun 2026",
    tags: ["Animación", "Comedia", "Aventura"],
    variant: "accent",
    posterNo: "09",
    poster: "posters/isleOfDogs.jpg",
    excerpt: "Wes Anderson construye con stop-motion una fábula japonesa sobre la lealtad y la burocracia, donde una manada de perros desterrados busca reencontrarse con su dueño.",
  },
  {
    id: "the-wolfpack",
    contentFile: "wolfpack",
    genre: "Documental",
    task: "Título de la tarea",
    film: "The Wolfpack",
    year: 2015,
    director: "Crystal Moselle",
    writer: "Crystal Moselle",
    producer: "Crystal Moselle, Izabella Tzenkova",
    studio: "Magnolia Pictures",
    cinematography: "Crystal Moselle",
    country: "Estados Unidos",
    runtime: "90 min",
    rating: 3,
    liked: false,
    watched: "23 Jun 2026",
    tags: ["Documental"],
    variant: "light",
    posterNo: "10",
    poster: "posters/theWolfpack.jpg",
    excerpt: "Crystal Moselle retrata a los hermanos Angulo, siete jóvenes criados en aislamiento en un apartamento de Manhattan que aprendieron sobre el mundo a través de las películas que reescenificaban.",
  },
  {
    id: "only-lovers-left-alive",
    contentFile: "onlyLoversLeftAlive",
    genre: "Drama / Terror",
    task: "Título de la tarea",
    film: "Only Lovers Left Alive",
    year: 2013,
    director: "Jim Jarmusch",
    writer: "Jim Jarmusch",
    producer: "Reinhard Brundig, Jeremy Thomas",
    studio: "Recorded Picture Company · Pandora Film",
    cinematography: "Yorick Le Saux",
    country: "Reino Unido / Alemania / Francia",
    runtime: "123 min",
    rating: 4,
    liked: false,
    watched: "24 Jun 2026",
    tags: ["Drama", "Romance", "Terror"],
    variant: "dark",
    posterNo: "11",
    poster: "posters/onlyLoversLeftAlive.jpg",
    excerpt: "Jim Jarmusch crea un retrato melancólico y elegante de dos vampiros centenarios que observan el decaimiento de la humanidad con una mezcla de amor eterno y fastidio existencial.",
  },
  {
    id: "we-need-to-talk-about-kevin",
    contentFile: "weNeedToTalkAboutKevin",
    genre: "Drama / Thriller",
    task: "Título de la tarea",
    film: "We Need to Talk About Kevin",
    year: 2011,
    director: "Lynne Ramsay",
    writer: "Lynne Ramsay, Rory Stewart Kinnear",
    producer: "Luc Roeg, Jennifer Fox",
    studio: "BBC Films · Oscilloscope Laboratories",
    cinematography: "Seamus McGarvey",
    country: "Reino Unido / Estados Unidos",
    runtime: "110 min",
    rating: 4,
    liked: false,
    watched: "29 Jun 2026",
    tags: ["Drama", "Thriller Psicológico"],
    variant: "light",
    posterNo: "12",
    poster: "posters/weNeedToTalkAboutKevin.jpg",
    excerpt: "Lynne Ramsay construye un devastador retrato de culpa y ambivalencia materna a través de una cronología fragmentada, explorando la relación entre Eva y su hijo Kevin antes de un acto de violencia inexplicable.",
  },
  {
    id: "amores-perros",
    contentFile: "amoresPerros",
    genre: "Drama / Thriller",
    task: "Título de la tarea",
    film: "Amores Perros",
    year: 2000,
    director: "Alejandro González Iñárritu",
    writer: "Guillermo Arriaga",
    producer: "Alejandro González Iñárritu, Martha Sosa Elizondo, Francisco González Compeán",
    studio: "Altavista Films · Zeta Film",
    cinematography: "Rodrigo Prieto",
    country: "México",
    runtime: "154 min",
    rating: 4,
    liked: false,
    watched: "30 Jun 2026",
    tags: ["Drama", "Thriller", "Crimen"],
    variant: "accent",
    posterNo: "13",
    poster: "posters/amoresPerros.jpg",
    excerpt: "Alejandro González Iñárritu debuta con una obra maestra del cine mexicano: tres historias entrelazadas por un accidente automovilístico que exploran la violencia, el amor y la redención en la Ciudad de México.",
  },
];

// ID de la película que aparece destacada en el encabezado.
// Cambia este valor al id de cualquier película para fijarla manualmente.
// Si se deja vacío (""), se elige automáticamente la mejor calificada.
const FEATURED_ID = "arrival";

window.PROFILE = PROFILE;
window.FILMS = FILMS;
window.FEATURED_ID = FEATURED_ID;
